### ISSUE TITLE
SendMessage API Error

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-nodejs#2123]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

By invoking SendMessage API, I am getting following error

NOTE: I am sending message to my contact

`Evaluation failed: TypeError: Cannot read properties of null (reading 'id') at Object.window.<computed>.<computed> [as sendMessage] (__puppeteer_evaluation_script__:1:298701)`

> middleware -> error Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'id')
    at Object.window.<computed>.<computed> [as sendMessage] (__puppeteer_evaluation_script__:1:298701)
    at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

### Expected Behavior

It should send message to my contact

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
- Debug info: {
  "WA_VERSION": "2.2134.10",
  "PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.20.8",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.82",
  "OS": "Linux 5.8",
  "START_TS": 1631617374089
}
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: 13.14.0
- npm: 7.6.3
```

**Comment by smashah** [comment]
Please can you show the exact curl request you are using to send the message

**Comment by alvaroespinola** [comment]
I have an issue with send reply with new 21 version, fixed the QR issue, but Reply with Whatsapp Beta not working

{"args":{"to":"595981111111@c.us","content":"*Maravilloso!!*","quotedMsgId":"false_5959811111114@c.us_4913D5667C53CB4F83CA2121D4DD734B"}}
{ success: true }
{ success: true }

**Comment by smashah** [comment]
@gafsel there is not enough context to replicate based on my testing.

Please share your config and any other information

**Comment by gafsel** [comment]
Hello @smashah 

I'm running the open-wa/wa-automate-nodejs in a node project within a docker container. The docker-compose is as follows:

```yaml

  browser:
    image: browserless/chrome:latest
    hostname: browser
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      CONNECTION_TIMEOUT: -1
      KEEP_ALIVE: 'true'
      WORKSPACE_EXPIRE_DAYS: 1
      ENABLE_CORS: 'true'
      CHROME_REFRESH_TIME: 86400000
      DEFAULT_BLOCK_ADS: 'true'
      FUNCTION_ENABLE_INCOGNITO_MODE: 'true'
      ENABLE_XVBF: 'true'
      CHROME_PATH: '/usr/bin/google-chrome'
      USE_CHROME_STABLE: 'true'
      NODE_ENV: 'production'

  app:
    build: .
    restart: on-failure
    depends_on:
      - browser
      - kafka
    environment:
      WA_BROWSER_WS_ENDPOINT: 'http://browser:3000'
      KAFKA_WS_SERVER: 'kafka:9092'
      WA_DISABLE_SPINS: 'true'

``` 

The package.json is as follows:

```json
{
  "name": "integracao-whatsapp",
  "version": "1.0.0",
  "description": "Integração com api open-wa/wa-automate para disponibilizar API Rest",
  "main": "app.js",
  "repository": "https://github.com/Main-Class/reminder-wa.git",
  "scripts": {
    "start": "node app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Willian.Bueno",
  "license": "ISC",
  "dependencies": {
    "@open-wa/wa-automate": "^4.22.4",
    "body-parser": "^1.19.0",
    "consign": "^0.1.6",
    "kafkajs": "^1.15.0",
    "uuid": "^3.4.0"
  }
}
```

The code where the error happens is the follow:

```javascript

async function sendMessage(data) {
      console.log('Mensagem enviada por ' + data.sessionId, {
              from: data.to,
              body: data.msg
          }
      );

      await client.sendText(data.to, data.msg);
}

```

If you need more information let me know.
